name: careerquest_flutter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.0.0
  intl: ^0.20.2
  supabase_auth_ui: ^0.5.5
  flutter_dotenv: ^6.0.0
  formz: ^0.8.0
  equatable: ^2.0.7
  injectable: ^2.7.1
  get_it: ^9.2.0
  go_router: ^17.0.1
  dio: ^5.9.0

  json_annotation: ^4.9.0
  stream_transform: ^2.1.1
  email_validator: ^2.1.17
  rxdart: ^0.28.0
 
dev_dependencies:
  bloc_lint: ^0.3.0
  bloc_test: ^10.0.0
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2
  mocktail: ^1.0.4

  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/features/authentication/
    - assets/images/features/job_search/
    
fonts:
  - family: AlteHaasGrotesk
    fonts:
      - asset: assets/fonts/AlteHaasGroteskRegular.ttf
      - asset: assets/fonts/AlteHaasGroteskBold.ttf
        weight: 700
  - family: FuturaPT
    fonts:
      - asset: assets/fonts/FuturaPTBook.otf
      - asset: assets/fonts/FuturaPTBold.otf
        weight: 700
  - family: NotoSans
    fonts:
      - asset: assets/fonts/NotoSans-VariableFont_wdth,wght.ttf
  
